name: Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Add permissions for the workflow
permissions:
  contents: read
  pull-requests: write
  checks: write
  statuses: write

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: blogdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore BlogApi.sln

    - name: Build
      run: dotnet build BlogApi.sln --no-restore

    - name: Run tests with coverage and publish results
      id: test_step
      run: |
        echo "Running tests..."
        dotnet test BlogApi.sln --no-build --verbosity normal \
          --logger "trx;LogFileName=test-results.trx" \
          --logger "console;verbosity=detailed" \
          /p:CollectCoverage=true \
          /p:CoverletOutputFormat=lcov \
          /p:CoverletOutput=./coverage/lcov.info \
          /p:Threshold=80
        echo "Test execution completed"
      continue-on-error: true

    - name: Check test results
      run: |
        echo "Checking for test results files..."
        find . -name "test-results.trx" -type f
        echo "Checking for coverage files..."
        find . -name "lcov.info" -type f
        ls -la ./coverage/ || echo "Coverage directory not found"

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          **/test-results.trx
          **/coverage/
        retention-days: 30

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: "**/test-results.trx"
      continue-on-error: true

    - name: Install lcov reporter
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov

    - name: Check if coverage file exists
      id: check_files
      run: |
        if [ -f "./coverage/lcov.info" ]; then
          echo "coverage_file_exists=true" >> $GITHUB_OUTPUT
          echo "Coverage file found"
        else
          echo "coverage_file_exists=false" >> $GITHUB_OUTPUT
          echo "Coverage file not found"
        fi

    - name: Generate coverage report
      if: steps.check_files.outputs.coverage_file_exists == 'true'
      run: |
        # Generate HTML report
        genhtml ./coverage/lcov.info --output-directory ./coverage/report
        
        # Get coverage percentage
        COVERAGE_PERCENT=$(lcov --summary ./coverage/lcov.info | grep -E "lines.*:" | awk '{print $2}')
        echo "COVERAGE_PERCENT=$COVERAGE_PERCENT" >> $GITHUB_ENV

    - name: Check coverage threshold
      if: steps.check_files.outputs.coverage_file_exists == 'true'
      run: |
        # Extract the numeric part of the coverage percentage
        COVERAGE_VALUE=$(echo "${{ env.COVERAGE_PERCENT }}" | sed 's/%//')
        if (( $(echo "$COVERAGE_VALUE < 80" | bc -l) )); then
          echo "Coverage is below the required threshold of 80%"
          exit 1
        else
          echo "Coverage meets the required threshold"
        fi

    - name: Publish coverage report as artifact
      if: steps.check_files.outputs.coverage_file_exists == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ./coverage/
        retention-days: 30

    - name: Display coverage summary
      run: |
        echo "## Test Coverage Report" >> $GITHUB_STEP_SUMMARY
        if [ "${{ steps.check_files.outputs.coverage_file_exists }}" == "true" ]; then
          echo "Coverage report has been generated and uploaded as an artifact." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Coverage | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|----------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Lines | ${{ env.COVERAGE_PERCENT }} | ✅ Meets threshold (80%) |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "You can download the full HTML report from the Artifacts section of this workflow run." >> $GITHUB_STEP_SUMMARY
          echo "To view the HTML report, download the artifact and open index.html in your browser." >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ No coverage report was generated. This may be due to tests failing or coverage not being collected properly." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Please check the test execution logs for more details." >> $GITHUB_STEP_SUMMARY
        fi